task: hsb-dsb_devsplit_fs5_v2
dataset_path: json
dataset_name: null
dataset_kwargs:
  data_files:
    test: /home/zc/wmt26/configs/eval/devsplits/sorbian_devsplit_fewshot_v2/eval/hsb-dsb_mt.jsonl
test_split: test
num_fewshot: 5
fewshot_config:
  sampler: first_n
  samples: !function utils.hsb_dsb_mt_shots
  doc_to_target: !function utils.target_dsb
fewshot_delimiter: "\n\n"
target_delimiter: " "
doc_to_text: "Translate the following Upper Sorbian text to Lower Sorbian. Put it in this format <dsb> Lower Sorbian translation </dsb>.\n<hsb> {{hsb}} </hsb>"
doc_to_target: "{{dsb}}"
generation_kwargs:
  until:
    - "<|endoftext|>"
    - "<|im_end|>"
  max_gen_toks: 256
  temperature: 1
  top_p: 1.0
  top_k: 20
  min_p: 0.0
  repetition_penalty: 1.0
filter_list:
  - name: "remove_tags"
    filter:
      - function: "strip_thinking"
      - function: "regex"
        regex_pattern: "<dsb>\\s*([\\s\\S]*?)\\s*(?:</dsb>|$)"
      - function: "take_first"
metric_list:
  - metric: bleu
  - metric: !function lm_eval.tasks.wmt26-lrl.utils.chrf_pp
    aggregation: chrf++
    higher_is_better: true
metadata:
  version: 2.0
